### ISSUE TITLE
Contribuciones Diego García García

### ISSUE THREAD

**Issue by uo282492** [Arquisoft/lomap_es4a#49]
- Realización de la pantalla inicial de la aplicación [#36](https://github.com/Arquisoft/lomap_es4a/issues/36)
- Posibilidad de loguearse en la aplicación a través de diferentes proveedores de pods SOLID [#39 ](https://github.com/Arquisoft/lomap_es4a/issues/39)
- Arreglos en la documentación

**Comment by uo282422** [comment]
Lo veo bien, te faltaría añadir que contribuiste en la investigación de componentes y todo el manejo de la sesión, así como tus puntos concretos de la documentación. Pero bien.

**Comment by gonzalo-rr** [comment]
Concuerdo con Manuel, también hiciste que se pudiese iniciar sesión con SOLID. Por lo demás perfecto.
