### ISSUE TITLE
Contribuciones Gonzalo Rodríguez

### ISSUE THREAD

**Issue by gonzalo-rr** [Arquisoft/lomap_es4a#50]
- Para la interacción con SOLID he creado una clase Point, un conjunto de funciones en los ficheros solidapi.ts y solidapiAdapter.ts para guardar datos en PODs y para crear los puntos y recuperarlos respectivamente [#33](https://github.com/Arquisoft/lomap_es4a/issues/33) y [#40](https://github.com/Arquisoft/lomap_es4a/issues/40)
- Para que se muestre la foto de perfil del usuario he modificado el componente Navbar  [#37](https://github.com/Arquisoft/lomap_es4a/issues/37)
- He modificado el componente Map para que cuando se pulse sobre el mapa se cree un nuevo marcador y para que cuando se carga el mapa se vean los marcadores de los puntos guardados en el POD [#40](https://github.com/Arquisoft/lomap_es4a/issues/40)

**Comment by uo282422** [comment]
Bien, te faltó mencionar tus apartados de la documentación, pero estoy de acuerdo.

**Comment by UO271477** [comment]
De acuerdo :)
