### ISSUE TITLE
Investigación sobre las tecnolgías a utilizar

### ISSUE THREAD

**Issue by gonzalo-rr** [Arquisoft/lomap_es4a#6]
Tomar decisiones en cuanto a las tecnologías a utilizar durante el desarrollo de la aplicación.

Algunos de los aspectos a considerar, aunque no los únicos son: Lenguaje de programación para la lógica de negocio, posible entorno o entornos de desarrollo a utilizar por los integrantes del equipo, base o bases de datos a utilizar, frameworks a utilizar.

Todas las decisiones tomadas deben ser debidamente justificadas. Todos los miembros del equipo pueden y deben contribuir en la toma de decisiones.

**Comment by UO271477** [comment]
**IDE a utilizar:**
Previamente habíamos comentado por encima en una reunión de utilizar WebStorm para desarrollar el proyecto.
 
- ¿No os parece mejor trabar con VS Code?
Me parece un entorno más fácil de manejar además de poder contar con una terminal dentro del IDE y poder utilizar comandos sin tener muchas ventanas abiertas

**Comment by uo282492** [comment]
Lo bueno de WebStorm es que es un IDE muy potente que dispone de una gran cantidad de [funcionalidades](https://www.jetbrains.com/es-es/webstorm/features/) a la hora de trabajar con tecnologías relacionadas con javascript (React, Node.js, ...). Esto implica que sea algo difícil de manejar al principio, porque cuenta con muchas opciones. Desde mi opinión, creo que, aunque al principio cueste trabajar con él, al final nos ayudará más que el VS Code, ya que este último es un editor de código más que un IDE especializado. No obstante, cada uno puede apostar por un IDE diferente y ver más adelante (una vez que los hayamos manejado con profundidad) cuál merece más la pena.

**Comment by uo281835** [comment]
Yo también creo que lo mejor sería usar WebStorm, principalmente por las facilidades que te da para JavaScript y este tipo de aplicaciones.
Además de que, como has dicho tú, es mejor usar un IDE dedicado a aplicaciones web directamente que VS Code con las extensiones de JavaScript, Node.js, etc.

**Comment by UO271477** [comment]
Perfecto.
