### ISSUE TITLE
Error al cargar el nombre de usuario de SOLID

### ISSUE THREAD

**Issue by uo282492** [Arquisoft/lomap_es4a#66]
En mi caso, cuando abro la navbar, no me aparece el nombre de usuario:
![Nombre de usuario no detectado](https://user-images.githubusercontent.com/113543063/230077024-d98a9e98-ae6e-447a-9d90-5d39aac1a8cb.png)

Esto se debe a que cuando cree mi perfil de SOLID, no incluí ningún nombre de perfil:
![Mi perfil de solid](https://user-images.githubusercontent.com/113543063/230077371-afc4027b-b215-4555-ae1f-49b5482f8937.png)

Concretamente, la propiedad que no tengo es la siguiente (código de Navbar.tsx):
![Propiedad usada en Navbar.tsx](https://user-images.githubusercontent.com/113543063/230077789-9ff4e8b3-e44f-4d9f-9fb6-bcd9abfb8fee.png)

Para solucionar esto, se me ocurren varias opciones:
- Buscar otra propiedad alternativa de la que se pueda extraer el nombre de perfil y de la que dispongan todos los usuarios.
- Seguir usando esa propiedad, pero usando además un condicional para comprobar que exista. En caso de que no exista, se podría poner un mensaje por defecto.
- Una mezcla de las dos anteriores.

Cabe destacar que comprobar con un condicional si existe una determinada propiedad es una buena práctica, ya que los perfiles de usuario de SOLID pueden variar bastante.

¿Cúal os parece una mejor opción?

**Comment by gonzalo-rr** [comment]
Hola Diego, he solucionado el bug, siguiendo la primera opción que planteas.

El caso es que, efectivamente, la propiedad VCARD.fn no siempre existe. En cambio, la propiedad FOAF.name sí existe al crear una cuenta en un proveedor de SOLID.

He hecho el cambio en mi rama, cuando tengamos una reunión os lo enseño y lo junto con develop.

En cuanto a comprobar que existe, estoy de acuerdo en que es una buena práctica y lo implementé.

![image](https://user-images.githubusercontent.com/61070475/230655938-642b0629-011b-4d89-a680-d19c6f370c59.png)
