### ISSUE TITLE
Contribuciones Manuel Palacios Entrega3

### ISSUE THREAD

**Issue by uo282422** [Arquisoft/lomap_es4a#83]
- Actualización de documentación respecto a las correcciones anteriores en mis partes de la documentación (posteriormente Gonzalo, tras revisar la documentación hizo cambios debido a la eliminación de la base de datos)
- Implementación del botón de logout.
- Implementación del listado de puntos.
- Implementación de las opciones de visualización (individual y colectiva) de los puntos
- Implementación del icono de edición
- Implementación del borrado de puntos y toda su interfaz. 
- Trabajo con Gonzalo en la refactorización de código de la lista de marcadores por un diccionario.
- Corrección del fallo visual al abrir Points.
- Configuración de alertas de edición, borrado y adición de puntos exitosa.
- Configuración de interfaz para campos erróneos.

**Comment by UO271477** [comment]
Perfecto.
Todo correcto 👍

**Comment by uo282492** [comment]
Very well 👍
