### ISSUE TITLE
Contribuciones Carlos Cesáreo Entrega3

### ISSUE THREAD

**Issue by UO271477** [Arquisoft/lomap_es4a#84]
- Implementación de la desaparición del punto al cancelar guardado
- Implementación del cambio del icono del Marker al guardarse
- Implementación de la interfaz de myFriends (Faltaría sacar los datos de la Promise para mostrarlos)
- Implementada la función que saca Amigos del POD
- Corrección de pequeños fallos encontrados por la aplicación
- Ayuda a Manuel para la detección del bug que cambiaba el CSS de la aplicación

**Comment by uo282422** [comment]
Bien trabajado

**Comment by gonzalo-rr** [comment]
Perfecto, buen trabajo.

**Comment by uo282492** [comment]
Todo perfecto 💯
