### ISSUE TITLE
Contribuciones Gonzalo Rodríguez Entrega 3

### ISSUE THREAD

**Issue by gonzalo-rr** [Arquisoft/lomap_es4a#85]
- Cambio de la interacción con SOLID para usar JSON-LD siguiendo la versión actual de la especificación de interoperabilidad.
- Adición de la funcionalidad (componente de React + función para SOLID) para editar puntos.
- Adición de la funcionalidad (componente de React + función para SOLID) para añadir puntos.
- Trabajo con Manuel en la refactorización de código de la lista de marcadores por un diccionario.
- Corrección del bug por el que no se mostraba el nombre del usuario.
- Corrección de bugs que surgieron durante la adición de funcionalidad de editar y añadir puntos.
- Modificación de varios apartados de la documentación para reflejar cambios en la implementación.

**Comment by UO271477** [comment]
Bien trabajado! 👍

**Comment by uo282492** [comment]
Bien hecho máquina 👍 🥇
