### ISSUE TITLE
Contribuciones Diego García Entrega3

### ISSUE THREAD

**Issue by uo282492** [Arquisoft/lomap_es4a#86]
- Implementación de carga de mapas
- Implementación de crear mapa
- Implementación de borrar mapa
- Modificación de las funciones de acceso a los POD para soportar varios mapas
- GUI de administración de mapas
- Tests unitarios y de aceptación del login

**Comment by gonzalo-rr** [comment]
Muy buen trabajo, todo perfecto.

**Comment by UO271477** [comment]
Todo correcto 👍
